test:
	python -m pytest --cov=simulator --cov-report=html simulator

run:
	python -m simulator fisher baseline
	python -m simulator fisher low
	python -m simulator fisher mid
	python -m simulator fisher high
