test:
	python -m pytest --cov=simulator --cov=vault --cov-report=html simulator vault

run:
	python -m simulator fisher baseline
	python -m simulator fisher low
	python -m simulator fisher mid
	python -m simulator fisher high
